<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Packaging;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Role;
use App\Models\Termin;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        Role::insert([
            ['name' => 'Owner'],
            ['name' => 'Admin'],
        ]);

        User::insert([
            [
                'name' => 'Era Frida Septiani',
                'role_id' => 1,
                'username' => 'era',
                'password' => bcrypt('era'),
            ]
        ]);

        Termin::insert([
            ['name' => 'Tunai', 'value' => 0],
        ]);

        ProductCategory::insert([
            ['id' => 1, 'name' => 'Our Trays'],
            ['id' => 2, 'name' => 'Mahar Collection'],
            ['id' => 3, 'name' => 'Paket Undangan Custom Ekonomis'],
            ['id' => 4, 'name' => 'Undangan Blangko'],
            ['id' => 5, 'name' => 'Rustic Series'],
            ['id' => 6, 'name' => 'Softcover Custom'],
            ['id' => 7, 'name' => 'Hardcover Custom'],
            ['id' => 8, 'name' => 'Undangan Custom'],
            ['id' => 9, 'name' => 'Web Invitation'],
            ['id' => 10, 'name' => 'Gelas'],
            ['id' => 11, 'name' => 'Botol / Tumbler'],
            ['id' => 12, 'name' => 'Tumbler Stainless'],
            ['id' => 13, 'name' => 'Mug & Poci'],
            ['id' => 14, 'name' => 'Mangkok & Piring'],
            ['id' => 15, 'name' => 'Asbak'],
            ['id' => 16, 'name' => 'Reed Difuser'],
            ['id' => 17, 'name' => 'Soap Dispenser'],
            ['id' => 18, 'name' => 'Fabric Pouch'],
            ['id' => 19, 'name' => 'Miniso Pouch'],
            ['id' => 20, 'name' => 'Pouch Resleting'],
            ['id' => 21, 'name' => 'Pouch Model Amplop'],
            ['id' => 22, 'name' => 'Premium Pouch'],
            ['id' => 23, 'name' => 'Card Holder'],
            ['id' => 24, 'name' => 'Paperbag'],
            ['id' => 25, 'name' => 'Hard Box'],
            ['id' => 26, 'name' => 'Paperbag Kertas'],
            ['id' => 27, 'name' => 'Totebag'],
            ['id' => 28, 'name' => 'Vynil Bening Tali Zara'],
            ['id' => 29, 'name' => 'Vynil Bening Tali Spunbon'],
            ['id' => 30, 'name' => 'Minibag Vynil Printing'],
            ['id' => 31, 'name' => 'Vynil Bening'],
            ['id' => 32, 'name' => 'Kanvas Motif / Polos'],
            ['id' => 33, 'name' => 'Vynil Printing'],
            ['id' => 34, 'name' => 'Kanvas Custom'],
            ['id' => 35, 'name' => 'Shopping Bag'],
            ['id' => 36, 'name' => 'Wooden Stuff'],
            ['id' => 37, 'name' => 'Cultery Set'],
            ['id' => 38, 'name' => 'Tasbih'],
            ['id' => 39, 'name' => 'Gunting Kuku (Meniped)'],
            ['id' => 40, 'name' => 'Kipas'],
            ['id' => 41, 'name' => 'Taplak PVC'],
            ['id' => 42, 'name' => 'Cermin'],
            ['id' => 43, 'name' => 'Ganci'],
            ['id' => 44, 'name' => 'Handuk'],
            ['id' => 45, 'name' => 'Tanaman Succulent'],
            ['id' => 46, 'name' => 'Madu Akasia'],
            ['id' => 47, 'name' => 'Handsanitizer'],
            ['id' => 48, 'name' => 'Jam'],
            ['id' => 49, 'name' => 'Jam + Speaker Bluetooth'],
            ['id' => 50, 'name' => 'Tempat Tissue'],
            ['id' => 51, 'name' => 'Payung'],
            ['id' => 52, 'name' => 'Corporate Souvenir'],
            ['id' => 53, 'name' => 'Hampers Exclusive'],
            ['id' => 54, 'name' => 'Paket Hampers'],
            ['id' => 55, 'name' => 'Seminar Kit'],
            ['id' => 56, 'name' => 'Souvenir Haji, Umroh & Pengajian'],
            ['id' => 57, 'name' => 'Birthday Souvenir Package'],
            ['id' => 58, 'name' => 'Bag Series'],
        ]);

        Packaging::insert([
            ['id' => 1, 'name' => 'Standard'],
            ['id' => 2, 'name' => 'Tray'],
            ['id' => 3, 'name' => 'Mika/Box'],
            ['id' => 4, 'name' => 'Box'],
            ['id' => 5, 'name' => 'Plastik'],
            ['id' => 6, 'name' => 'Doublewall'],
            ['id' => 7, 'name' => 'Hardbox'],
            ['id' => 8, 'name' => 'Rustic Box'],
        ]);

        Product::insert([
            ['price' => 60000, 'name' => 'Hazel Gold', 'product_category_id' => 1, 'packaging_id' => 2, 'minimum_order' => 1],
            ['price' => 60000, 'name' => 'Classic Silver', 'product_category_id' => 1, 'packaging_id' => 2, 'minimum_order' => 1],
            ['price' => 60000, 'name' => 'Wooden Rustic', 'product_category_id' => 1, 'packaging_id' => 2, 'minimum_order' => 1],
            ['price' => 60000, 'name' => 'Soldi White', 'product_category_id' => 1, 'packaging_id' => 2, 'minimum_order' => 1],
            ['price' => 75000, 'name' => 'Terrarium Glass', 'product_category_id' => 1, 'packaging_id' => 2, 'minimum_order' => 1],
            ['price' => 75000, 'name' => 'Crystal Glass', 'product_category_id' => 1, 'packaging_id' => 2, 'minimum_order' => 1],
            ['price' => 450000, 'name' => 'Carya', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 750000, 'name' => 'Maharani', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 500000, 'name' => 'Isvara', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 650000, 'name' => 'Karuna', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 600000, 'name' => 'Lastari', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 600000, 'name' => 'Betari', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 600000, 'name' => 'Savitri', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 750000, 'name' => 'Ghayatri', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 600000, 'name' => 'Jelita', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 650000, 'name' => 'Luna', 'product_category_id' => 2, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 12000, 'name' => 'UCE 1', 'product_category_id' => 3, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 13000, 'name' => 'UCE 2', 'product_category_id' => 3, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 13000, 'name' => 'UCE 3', 'product_category_id' => 3, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 14000, 'name' => 'UCE 4', 'product_category_id' => 3, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 16000, 'name' => 'UCE 5', 'product_category_id' => 3, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 20000, 'name' => 'UCE 6', 'product_category_id' => 3, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 2950, 'name' => 'Indie', 'product_category_id' => 4, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 2950, 'name' => 'Be You', 'product_category_id' => 4, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 2950, 'name' => 'Samara', 'product_category_id' => 4, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 7000, 'name' => 'R1-R2', 'product_category_id' => 5, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 8000, 'name' => 'R3-R4', 'product_category_id' => 5, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 9500, 'name' => 'R5', 'product_category_id' => 5, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 8000, 'name' => 'R6', 'product_category_id' => 5, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 10500, 'name' => 'R7 & R15', 'product_category_id' => 5, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 10500, 'name' => 'R8', 'product_category_id' => 5, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 8500, 'name' => 'R9', 'product_category_id' => 5, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 8500, 'name' => 'R10', 'product_category_id' => 5, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 8000, 'name' => 'R11', 'product_category_id' => 5, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 11000, 'name' => 'SC L2', 'product_category_id' => 6, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 8500, 'name' => 'SC L3', 'product_category_id' => 6, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 20000, 'name' => 'SC L2 + Amplop', 'product_category_id' => 6, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 15500, 'name' => 'SC L3 + Amplop', 'product_category_id' => 6, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 4500, 'name' => 'SC L2/L3 + Belt', 'product_category_id' => 6, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 8500, 'name' => 'SC Wayang', 'product_category_id' => 6, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 11500, 'name' => 'SC Sliding', 'product_category_id' => 6, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 16000, 'name' => 'SC Sliding + Amplop', 'product_category_id' => 6, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 16000, 'name' => 'HC L2', 'product_category_id' => 7, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 18000, 'name' => 'HC L3', 'product_category_id' => 7, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 24000, 'name' => 'HC L2/L3 + Amplop', 'product_category_id' => 7, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 28000, 'name' => 'HC L2/L3 + Amplop (Up Size)', 'product_category_id' => 7, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 14000, 'name' => 'Single Hard Rami', 'product_category_id' => 7, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 20500, 'name' => 'Single Hard + Amplop', 'product_category_id' => 7, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 23000, 'name' => 'Single Hard Amplop', 'product_category_id' => 7, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 25000, 'name' => 'Single Hard Amplop 2 Sisi', 'product_category_id' => 7, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 12000, 'name' => 'Double Slider Amplop', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 8500, 'name' => 'Double Slider No Amplop', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 12000, 'name' => 'Arunika Series', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 8500, 'name' => 'Newspaper', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 18000, 'name' => 'Semi Envelope (Hardcover Bagian Isi)', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 15500, 'name' => 'Semi Envelope (Softcover Full Design)', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 16000, 'name' => 'SHC Semi Envelope 1', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 13000, 'name' => 'SHC Semi Envelope 2', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 21500, 'name' => 'Kalkir Series', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 50],
            ['price' => 10500, 'name' => 'Passport', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 37500, 'name' => 'Akrilik Series (Amplop 1 Sisi)', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 44500, 'name' => 'Akrilik Series (Amplop 2 Sisi)', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 11500, 'name' => 'Kipas Amplop', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 12500, 'name' => 'Half Round Semi Amplop', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 100],
            ['price' => 60000, 'name' => 'Guest Book', 'product_category_id' => 8, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 200000, 'name' => 'Premium Package (Foto)', 'product_category_id' => 9, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 150000, 'name' => 'Premium Package (Tanpa Foto)', 'product_category_id' => 9, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 200000, 'name' => 'Exclusive Package (Foto)', 'product_category_id' => 9, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 150000, 'name' => 'Exclusive Package (Tanpa Foto)', 'product_category_id' => 9, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 250000, 'name' => 'Art Package (Foto)', 'product_category_id' => 9, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 200000, 'name' => 'Art Package (Tanpa Foto)', 'product_category_id' => 9, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 200000, 'name' => 'Adat Package', 'product_category_id' => 9, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 250000, 'name' => 'Special Motion Art Series (Foto)', 'product_category_id' => 9, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 200000, 'name' => 'Special Motion Art Series (Tanpa Foto)', 'product_category_id' => 9, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 4500, 'name' => 'Sloki 8cm Doff', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 4000, 'name' => 'Sloki 8cm Bening', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 5500, 'name' => 'Sloki 10cm Doff', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 5000, 'name' => 'Sloki 10cm Bening', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 6500, 'name' => 'Sloki 12cm Doff', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 6000, 'name' => 'Sloki 12cm Bening', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 13000, 'name' => 'Jar Tutup 13 cm Doff', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 12500, 'name' => 'Jar Tutup 13 cm Bening', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 9750, 'name' => 'Daisy', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 7750, 'name' => 'Aesthetic', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8000, 'name' => 'Gagang Belt', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 9000, 'name' => 'Ale', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8000, 'name' => 'Picca', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8000, 'name' => 'Kopi', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 9000, 'name' => 'Hoho', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 9000, 'name' => 'Tuscany 10x12cm', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 7500, 'name' => 'Tabung 16.5cm', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Enamel 7cm', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 7000, 'name' => 'G Gendut/Slim 9cm Doff', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 6500, 'name' => 'G Gendut/Slim 9cm Bening', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8500, 'name' => 'Crown', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8500, 'name' => 'Diamond', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Milk', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Kaca Bear', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 12500, 'name' => 'Aesthetic Tinggi', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8500, 'name' => 'Jar Pastel', 'product_category_id' => 10, 'packaging_id' => 1, 'minimum_order' => 1],

            ['price' => 7000, 'name' => 'Botol Kaca 420mL Bening', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 7500, 'name' => 'Botol Kaca 420mL Doff', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 7500, 'name' => 'My Bottle Kotak 420mL', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8000, 'name' => 'Nice 450mL', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 7500, 'name' => 'Kaktus 450mL', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8000, 'name' => 'Kristal 450mL', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 9500, 'name' => 'Sweet 450mL', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8000, 'name' => 'Six Up 450mL', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Macaroon', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 18000, 'name' => 'Smiggle', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Youth', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Sailing Kids', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 7500, 'name' => 'Rabbit', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Daisy', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 11000, 'name' => 'Deer', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Pure Love S', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8500, 'name' => 'Mini Bottle', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Lampion', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 8500, 'name' => 'Kaca Tali', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 9000, 'name' => 'Portable Cup 600mL', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 10000, 'name' => 'Portable Cup 800mL', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 15000, 'name' => 'Pure Love', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 22000, 'name' => 'Insert Paper', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 12000, 'name' => 'Dream 1L', 'product_category_id' => 11, 'packaging_id' => 1, 'minimum_order' => 1],

            ['price' => 28000, 'name' => 'Mug Egg', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 30000, 'name' => 'Cofee Stainless 1', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 30000, 'name' => 'Cofee Stainless 2', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 30000, 'name' => 'Mug Stainless', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 57000, 'name' => 'Mug Stainless Gradasi', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 45000, 'name' => 'Arizona', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 39000, 'name' => 'Mug Oval', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 30000, 'name' => 'Travel Tumbler', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 27500, 'name' => 'Pocket Tumbler 150mL', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 28500, 'name' => 'Pocket Tumbler 250mL', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 20000, 'name' => 'Sport 500mL', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 30000, 'name' => 'Sport 750mL', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 29500, 'name' => 'Travel Hook', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 24000, 'name' => 'Niagara', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 27000, 'name' => 'Life', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 28000, 'name' => 'LED Suhu', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 39000, 'name' => 'Vacuum Set', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 59000, 'name' => 'Catein Premium', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 69000, 'name' => 'Sakura Bambu', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 47500, 'name' => 'Mug Cruiser', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 30000, 'name' => 'Mini Vacuum', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 40000, 'name' => 'Elite', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 34000, 'name' => 'Americano', 'product_category_id' => 12, 'packaging_id' => 1, 'minimum_order' => 1],

            ['price' => 14500, 'name' => 'Digital Putih', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 15000, 'name' => 'Digital Hitam', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 32000, 'name' => 'Susu + Sendok', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 20500, 'name' => 'Cangkir + Lepek', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 20000, 'name' => 'DMG 1', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 21000, 'name' => 'DMG 6', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 25000, 'name' => 'DMG 11', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 20000, 'name' => 'DMG 46', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 45500, 'name' => 'Poci Tumpuk', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 72500, 'name' => 'Poci Yasmin', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
            ['price' => 24500, 'name' => 'Namo + Sendok', 'product_category_id' => 13, 'packaging_id' => 1, 'minimum_order' => 1],
        ]);

    }
}
